# Lanti/LetsEncrypt
#
# VERSION               1.0.0

FROM lantosistvan_base:latest
MAINTAINER Istvan Lantos <kerozin.joe@gmail.com>
LABEL Description="Let's Encrypt" Vendor="Istvan Lantos" Version="1.0"
