version: 2
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: app_cadvisor
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
  base:
    build:
      context: ./base
      args:
        buildno: 1
      build: ./base
      container_name: app_base
      net: "none"
      volumes:
        - /var/www:rw
  node:
    build:
      context: ./node
      args:
        buildno: 2
      build: ./node
      container_name: app_node
      #net: "none"
      volumes_from:
        - base
#volumes:
#  ffmpeg_dir:
#    driver: default
# Changing the settings of the app-wide default network
#networks:
#  default:
    # Use the overlay driver for multi-host communication
#    driver: host
