version: '2'
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: lantosistvan_cadvisor
    depends_on:
      - app
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    #networks:
    #  - front-tier
  base:
    build: ./base
    image: lantosistvan_base
    container_name: lantosistvan_base
    network_mode: "none"
  node:
    build: ./node
    image: lantosistvan_node
    container_name: lantosistvan_node
    depends_on:
      - base
    network_mode: "none"
  nginx:
    build: ./nginx
    image: lantosistvan_nginx
    container_name: lantosistvan_nginx
    depends_on:
      - node
    command: /bin/dash -c "/usr/sbin/nginx"
    ports:
      - "8080:8080"
      - "443:443"
    volumes:
      - /var/cache/nginx
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - front-tier
  app:
    build: ./app
    image: lantosistvan_app
    container_name: lantosistvan_app
    depends_on:
      - nginx
    environment:
      - NODE_ENV=production
      - DEBUG=lantosistvan-portfolio:*,i18n:*,gulp:*,gulp-live-server:*
    #command: npm install
    command: /bin/dash -c "npm install && npm start"
    ports:
      - "8081:8081"
    volumes:
      #- "../app:/root/www/lantosistvan:rw"
      - "../app:/root/www/lantosistvan:rw"
    networks:
      - front-tier
networks:
  front-tier:
    driver: bridge
  #back-tier:
  #  driver: bridge
