version: '2'

services:
  #cadvisor:
  #  image: google/cadvisor:latest
  #  container_name: lantosistvan_cadvisor
  #  depends_on:
  #    - app
  #  ports:
  #    - "8079:8080"
  #  volumes:
  #    - "/:/rootfs:ro"
  #    - "/var/run:/var/run:rw"
  #    - "/sys:/sys:ro"
  #    - "/var/lib/docker/:/var/lib/docker:ro"
  #  #networks:
  #  #  - front-tier
  base:
    build: ./base
    image: lantosistvan_base
    container_name: lantosistvan_base
    command: echo "Data-only container"
    network_mode: "none"
  node:
    build: ./node
    image: lantosistvan_node
    container_name: lantosistvan_node
    command: "Data-only container"
    depends_on:
      - base
    network_mode: "none"
  app:
    build: ./app
    image: lantosistvan_app
    container_name: lantosistvan_app
    depends_on:
      #- letsencrypt
      - node
    environment:
      - NODE_ENV=production
      - DEBUG=lantosistvan-portfolio:*,i18n:*,gulp:*,gulp-live-server:*
      #- PRIVATE_IP_DOCKER=172.16.238.11
      - PRIVATE_IP_DOCKER=172.16.238.11
      - PORT=8081
    command: npm install && npm start
    ####ports:
      #- "10.0.2.15:8081:8081"
      ####- "8081:8081"
    volumes:
      #- "../app:/root/www/lantosistvan:rw"
      - lantosistvan_app:/root/www/lantosistvan:rw
    networks:
      #lantosistvan_front:
      #  ipv4_address: 172.16.238.11
      #  ipv6_address: 2001:3984:3989::11
      lantosistvan_back:
        ipv4_address: 172.16.238.11
        ipv6_address: 2001:3984:3989::11
  nginx:
    build: ./nginx
    image: lantosistvan_nginx
    container_name: lantosistvan_nginx
    depends_on:
      - app
    command: /bin/dash -c "/usr/sbin/nginx"
    ports:
      #- "0.0.0.0:80:80"
      - "80:80"
      - "443:443"
      ####- "8080:8080"
    volumes:
      - /var/cache/nginx
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/etc/nginx/conf.d:/etc/nginx/conf.d:ro
      #- ../app/public:/var/www/html/public:ro
      #- ../app/public/ftp:/var/www/html/ftp:ro
      - lantosistvan_nginx_public:/var/www/html/public:ro
      - lantosistvan_nginx_public_ftp:/var/www/html/ftp:ro
    ####extra_hosts:
     #- "localhost.cinematicheart.com:172.16.238.10"
     ####- "localhost.cinematicheart.com:127.0.0.1"
    networks:
      lantosistvan_back:
        ipv4_address: 172.16.238.10
        ipv6_address: 2001:3984:3989::10
      lantosistvan_front:
        ipv4_address: 173.16.238.10
        ipv6_address: 2002:3984:3989::10
    ulimits:
      nproc: 65535
      nofile:
        #soft: 20000
        #hard: 40000
        soft: 10240
        hard: 20480
  #letsencrypt:
  #  build: ./letsencrypt
  #  image: lantosistvan_letsencrypt
  #  container_name: lantosistvan_letsencrypt
  #  depends_on:
  #    - nginx
  #  networks:
  #    - lantosistvan_front

volumes:
  lantosistvan_app:
    #driver: local
    driver_opts:
      uid: 500
      gid: 500
      device: ../app
  lantosistvan_nginx_public:
    #driver: local
    driver_opts:
      uid: 500
      gid: 500
      device: ../app/public
  lantosistvan_nginx_public_ftp:
    #driver: local
    driver_opts:
      uid: 500
      gid: 500
      device: ../app/public/ftp

networks:
  lantosistvan_back:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
          #aux_addresses:
          #  localhost.cinematicheart.com: 172.16.238.10
        - subnet: 2001:3984:3989::/64
          gateway: 2001:3984:3989::1
        #- subnet: 172.28.0.0/16
        #  ip_range: 172.28.5.0/24
        #  gateway: 172.28.5.254
        #  aux_addresses:
        #    host1: 172.28.1.5
        #    host2: 172.28.1.6
        #    host3: 172.28.1.7
  lantosistvan_front:
    driver: bridge
    driver_opts:
      com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 173.16.238.0/24
          gateway: 173.16.238.1
          #aux_addresses:
          #  localhost.cinematicheart.com: 172.16.238.10
        - subnet: 2002:3984:3989::/64
          gateway: 2002:3984:3989::1
        #- subnet: 172.28.0.0/16
        #  ip_range: 172.28.5.0/24
        #  gateway: 172.28.5.254
        #  aux_addresses:
        #    host1: 172.28.1.5
        #    host2: 172.28.1.6
        #    host3: 172.28.1.7
