version: '2'

services:
  #cadvisor:
  #  image: google/cadvisor:latest
  #  container_name: lantosistvan_cadvisor
  #  depends_on:
  #    - app
  #  ports:
  #    - "8079:8080"
  #  volumes:
  #    - "/:/rootfs:ro"
  #    - "/var/run:/var/run:rw"
  #    - "/sys:/sys:ro"
  #    - "/var/lib/docker/:/var/lib/docker:ro"
  #  #networks:
  #  #  - front-tier
  base:
    build: ./base
    image: lantosistvan_base
    container_name: lantosistvan_base
    network_mode: "none"
  node:
    build: ./node
    image: lantosistvan_node
    container_name: lantosistvan_node
    depends_on:
      - base
    network_mode: "none"
  nginx:
    build: ./nginx
    image: lantosistvan_nginx
    container_name: lantosistvan_nginx
    depends_on:
      - node
    command: /bin/dash -c "/usr/sbin/nginx"
    ports:
      - "80:8080"
      - "443:443"
    volumes:
      - /var/cache/nginx
      - ./nginx/etc/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      front-tier:
        ipv4_address: 172.16.238.10
        #ipv6_address: 2001:3984:3989::10
  app:
    build: ./app
    image: lantosistvan_app
    container_name: lantosistvan_app
    depends_on:
      - nginx
    environment:
      - NODE_ENV=production
      - DEBUG=lantosistvan-portfolio:*,i18n:*,gulp:*,gulp-live-server:*
      - PRIVATE_IP_DOCKER=172.16.238.11
      - PORT=8081
    command: /bin/dash -c "npm install && npm start"
    ports:
      - "8081:8081"
    volumes:
      - "../app:/root/www/lantosistvan:rw"
    networks:
      front-tier:
        ipv4_address: 172.16.238.11
        #ipv6_address: 2001:3984:3989::11
networks:
  front-tier:
    driver: bridge
    #driver_opts:
    #  com.docker.network.enable_ipv6: "true"
    ipam:
      driver: default
      config:
        - subnet: 172.16.238.0/24
          gateway: 172.16.238.1
          aux_addresses:
            localhost.cinematicheart.com: 172.16.238.10
        #- subnet: 2001:3984:3989::/64
        #  gateway: 2001:3984:3989::1
        #- subnet: 172.28.0.0/16
        #  ip_range: 172.28.5.0/24
        #  gateway: 172.28.5.254
        #  aux_addresses:
        #    host1: 172.28.1.5
        #    host2: 172.28.1.6
        #    host3: 172.28.1.7
  #back-tier:
  #  driver: bridge
