version: '2'
services:
  cadvisor:
    image: google/cadvisor:latest
    container_name: lantosistvan_cadvisor
    depends_on:
      - app
    ports:
      - "8080:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
    #networks:
    #  - front-tier
  base:
    build: ./base
    image: lantosistvan_base
    container_name: lantosistvan_base
    network_mode: "none"
  node:
    build: ./node
    image: lantosistvan_node
    container_name: lantosistvan_node
    depends_on:
      - base
    network_mode: "none"
  app:
    build: ./app
    image: lantosistvan_app
    container_name: lantosistvan_app
    depends_on:
      - node
    environment:
      - NODE_ENV=production
      - DEBUG=lantosistvan-portfolio:*,i18n:*,gulp:*,gulp-live-server:*
    #command: npm install
    command: /bin/dash -c "npm install && npm start"
    ports:
      - "80:3000"
    volumes:
      #- "../app:/root/www/lantosistvan:rw"
      - "../app:/root/www/lantosistvan:rw"
    networks:
      - front-tier
networks:
  front-tier:
    driver: bridge
  #back-tier:
  #  driver: bridge
