version: '2'
services:
  app:
    build: .
    image: lwan
    container_name: lwan_lwan
    command: /bin/dash -c "build/lwan/lwan -r /lwan/wwwroot -l *:8080"
    ports:
      - "80:8080"
    volumes:
      - "./lwan.conf:/lwan/lwan.conf:ro"
      - "./wwwroot/lantosistvan/:/lwan/wwwroot/lantosistvan/:rw"
    networks:
      - lwan
networks:
  lwan:
    driver: bridge
